### ISSUE TITLE
Licenses: "Apache 2.0 and MIT", or "Apache 2.0 or MIT"

### ISSUE THREAD

**Issue by mgeisler** [asomers/mockall#529]
Hi @asomers,

I'm working on importing `mockall` and `mockall_derive` to AOSP. Our tooling flagged the license file: is the crate licensed under "Apache 2.0 _or_ MIT" (as is usual in Rust), or is it licensed with both licenses applying at the same time?

The `license` field in `Cargo.toml` currently says

```toml
[package]
license = "MIT/Apache-2.0"
```

and I believe it might have been intended to let it say

```toml
[package]
license = "MIT OR Apache-2.0"
```

as per the [Cargo reference](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields).

We pick the Apache 2.0 license when given the choice ([random example](https://cs.android.com/android/platform/superproject/+/main:external/rust/crates/url/LICENSE)), but here our tooling got confused.
